working on the dockerfile for the domain driven design. WIP

diff --git a/deployment/Dockerfile b/deployment/Dockerfile
--- a/deployment/Dockerfile
+++ b/deployment/Dockerfile
@@ -1,23 +1,21 @@
-﻿# FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
-# FROM mcr.microsoft.com/dotnet/aspnet:7.0.11-bookworm-slim-arm64v8 AS base
-FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
+﻿FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
 WORKDIR /app
 EXPOSE 80
 EXPOSE 443
 
-# FROM mcr.microsoft.com/dotnet/sdk:7.0.401-bookworm-slim-arm64v8 AS build
 FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS build
 WORKDIR /src
-COPY ["Portfolio.WebUi.csproj", "Portfolio.WebUi/"]
+COPY ["Portfolio.WebUi/.", "Portfolio.WebUi/"]
+COPY ["Portfolio.Domain/.", "Portfolio.Domain/"]
+COPY ["Portfolio.DataAccess/.", "Portfolio.DataAccess/"]
 RUN if [ ! -f Portfolio.WebUi/Portfolio.WebUi.csproj ]; then echo "File(s) missing for RESTORE! Check the paths."; exit 1; fi
 RUN dotnet restore "Portfolio.WebUi/Portfolio.WebUi.csproj"
 
-#COPY . .
 COPY . /src/Portfolio.WebUi/
-WORKDIR "/src/Portfolio.WebUi"
-RUN if [ ! -f Portfolio.WebUi.csproj ]; then echo "File(s) missing BUILD! Check the paths."; exit 1; fi
-RUN if [ ! -f Program.cs ]; then echo "File(s) missing PROGRAM.CS! Check the paths."; exit 1; fi
-RUN dotnet build "Portfolio.WebUi.csproj" -c Release -o /app/build
+WORKDIR "/src"
+RUN if [ ! -f Portfolio.WebUi/Portfolio.WebUi.csproj ]; then echo "File(s) missing BUILD! Check the paths."; exit 1; fi
+RUN if [ ! -f Portfolio.WebUi/Program.cs ]; then echo "File(s) missing PROGRAM.CS! Check the paths."; exit 1; fi
+RUN dotnet build "Portfolio.WebUi/Portfolio.WebUi.csproj" -c Release -o /app/build
 
 FROM build AS publish
 RUN dotnet publish "Portfolio.WebUi.csproj" -c Release -o /app/publish /p:UseAppHost=false
